import { Punishment } from "./components/banscomms";
import { UserData } from "./components/stats";

export const userData: UserData[] = [
  {
    rank: 4,
    username: "imaginative",
    experience: 110925,
    title: "Фиолетовый Единорог",
    kills: 3646,
    deaths: 1894,
    kdr: 1.92,
    headshots: 1995,
    playtime: "3 недели",
    lastGame: "20.04.2025 в 21:46",
  },
  {
    rank: 5,
    username: "ночной_волк",
    experience: 108450,
    title: "Тень Арены",
    kills: 3590,
    deaths: 1920,
    kdr: 1.87,
    headshots: 1902,
    playtime: "2 недели",
    lastGame: "19.04.2025 в 23:15",
  },
  {
    rank: 6,
    username: "зверобой",
    experience: 113000,
    title: "Грозный Воин",
    kills: 3800,
    deaths: 2000,
    kdr: 1.9,
    headshots: 2001,
    playtime: "3 недели",
    lastGame: "21.04.2025 в 20:30",
  },
  {
    rank: 7,
    username: "тихий_убийца",
    experience: 107800,
    title: "Мастер Тени",
    kills: 3550,
    deaths: 1900,
    kdr: 1.87,
    headshots: 1850,
    playtime: "2 недели",
    lastGame: "22.04.2025 в 19:00",
  },
  {
    rank: 3,
    username: "властелин",
    experience: 120000,
    title: "Командир Армии",
    kills: 3900,
    deaths: 1800,
    kdr: 2.17,
    headshots: 2100,
    playtime: "4 недели",
    lastGame: "20.04.2025 в 22:00",
  },
  {
    rank: 2,
    username: "стальной_дракон",
    experience: 125500,
    title: "Железный Боец",
    kills: 4000,
    deaths: 1850,
    kdr: 2.16,
    headshots: 2200,
    playtime: "4 недели",
    lastGame: "18.04.2025 в 21:10",
  },
  {
    rank: 8,
    username: "невидимка",
    experience: 105000,
    title: "Призрачный Убийца",
    kills: 3400,
    deaths: 1800,
    kdr: 1.89,
    headshots: 1750,
    playtime: "2 недели",
    lastGame: "17.04.2025 в 20:45",
  },
  {
    rank: 1,
    username: "кровавый_волк",
    experience: 130000,
    title: "Легенда Битвы",
    kills: 4200,
    deaths: 1700,
    kdr: 2.47,
    headshots: 2300,
    playtime: "5 недель",
    lastGame: "16.04.2025 в 22:25",
  },
  {
    rank: 9,
    username: "буря",
    experience: 100000,
    title: "Быстрый Удар",
    kills: 3300,
    deaths: 1900,
    kdr: 1.74,
    headshots: 1650,
    playtime: "2 недели",
    lastGame: "20.04.2025 в 18:00",
  },
  {
    rank: 10,
    username: "ледяной_король",
    experience: 95000,
    title: "Повелитель Севера",
    kills: 3100,
    deaths: 1850,
    kdr: 1.68,
    headshots: 1500,
    playtime: "1 неделя",
    lastGame: "15.04.2025 в 19:40",
  },
];

// export const punishments: Punishment[] = [
//   {
//     player: "XionKila",
//     reason: "1.2 Отказ от проверки",
//     duration: "4 нед. 1 дн.",
//     admin: "Дымок",
//   },
//   {
//     player: "notchnik",
//     reason: "1.1 Использование программ/читов",
//     duration: "Навсегда",
//     admin: "Дымок",
//   },
//   {
//     player: "дядя СЕРГЕЙ",
//     reason: "4.2 Плагиат админа",
//     duration: "1 дн. 22 ч.",
//     admin: "Дымок",
//   },
//   {
//     player: "creater",
//     reason: "1.2 Отказ от проверки",
//     duration: "Навсегда",
//     admin: "Дымок",
//   },
//   {
//     player: "крутой",
//     reason: "1.2 Отказ от проверки",
//     duration: "4 нед. 1 дн.",
//     admin: "Neperl0vкаʳᵐˣ",
//   },
//   {
//     player: "Ivan_Zolupka",
//     reason: "1.2 Отказ от проверки",
//     duration: "4 нед. 1 дн.",
//     admin: "Yanka318",
//   },
//   {
//     player: "silek",
//     reason: "2.11",
//     duration: "Навсегда",
//     admin: "Neperl0vкаʳᵐˣ",
//   },
//   {
//     player: "creater",
//     reason: "1.2 Отказ от проверки",
//     duration: "4 нед. 1 дн.",
//     admin: "Дымок",
//   },
//   {
//     player: "крутой",
//     reason: "1.2 Отказ от проверки",
//     duration: "4 нед. 1 дн.",
//     admin: "Neperl0vкаʳᵐˣ",
//   },
//   {
//     player: "creater",
//     reason: "1.2 Отказ от проверки",
//     duration: "4 нед. 1 дн.",
//     admin: "Дымок"
//   },
//   {
//     player: "крутой",
//     reason: "1.2 Отказ от проверки",
//     duration: "Навсегда",
//     admin: "Neperl0vкаʳᵐˣ"
//   },
//   {
//     player: "creater",
//     reason: "1.2 Отказ от проверки",
//     duration: "4 нед. 1 дн.",
//     admin: "Дымок"
//   },
//   {
//     player: "крутой",
//     reason: "1.2 Отказ от проверки",
//     duration: "4 нед. 1 дн.",
//     admin: "Neperl0vкаʳᵐˣ"
//   },
// ];
